#ifndef AZ_MACROS_DEBUG
#define AZ_MACROS_DEBUG

//#define DIAG_LOG_MODE

#ifdef DIAG_LOG_MODE
#define LOG_SYS(t, s) (diag_log format[t, s])
#define LOG_SYS_FILELINE(t, s) (diag_log format["%1(<%2>:%3) %4", format[t, ""], __FILE__, __LINE__ + 1, s])
#else
#define LOG_SYS(t, s) (systemChat format[t, s])
#define LOG_SYS_FILELINE(t, s) (systemChat format["%1(<%2>:%3) %4", format[t, ""], __FILE__, __LINE__ + 1, s])
#endif




#ifdef TRACE_MODE

#define TRACE(MESSAGE) LOG_SYS('[TRACE]: %1',MESSAGE)
#define TRACE_1(MESSAGE,ARG1) TRACE(FORMAT_1(MESSAGE,ARG1))
#define TRACE_2(MESSAGE,ARG1,ARG2) TRACE(FORMAT_2(MESSAGE,ARG1,ARG2))
#define TRACE_3(MESSAGE,ARG1,ARG2,ARG3) TRACE(FORMAT_3(MESSAGE,ARG1,ARG2,ARG3))
#define TRACE_4(MESSAGE,ARG1,ARG2,ARG3,ARG4) TRACE(FORMAT_4(MESSAGE,ARG1,ARG2,ARG3,ARG4))
#define TRACE_5(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5) TRACE(FORMAT_5(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5))
#define TRACE_6(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6) TRACE(FORMAT_6(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6))
#define TRACE_7(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7) TRACE(FORMAT_7(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7))
#define TRACE_8(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7,ARG8) TRACE(FORMAT_8(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7,ARG8))

#else

#define TRACE(MESSAGE) /* disabled */
#define TRACE_1(MESSAGE,ARG1) /* disabled */
#define TRACE_2(MESSAGE,ARG1,ARG2) /* disabled */
#define TRACE_3(MESSAGE,ARG1,ARG2,ARG3) /* disabled */
#define TRACE_4(MESSAGE,ARG1,ARG2,ARG3,ARG4) /* disabled */
#define TRACE_5(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5) /* disabled */
#define TRACE_6(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6) /* disabled */
#define TRACE_7(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7) /* disabled */
#define TRACE_8(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7,ARG8) /* disabled */

#endif

#ifdef DEBUG_MODE

#define ERROR(MESSAGE) LOG_SYS_FILELINE('[ERROR]: %1',MESSAGE)
#define ERROR_1(MESSAGE,ARG1) ERROR(FORMAT_1(MESSAGE,ARG1))
#define ERROR_2(MESSAGE,ARG1,ARG2) ERROR(FORMAT_2(MESSAGE,ARG1,ARG2))
#define ERROR_3(MESSAGE,ARG1,ARG2,ARG3) ERROR(FORMAT_3(MESSAGE,ARG1,ARG2,ARG3))
#define ERROR_4(MESSAGE,ARG1,ARG2,ARG3,ARG4) ERROR(FORMAT_4(MESSAGE,ARG1,ARG2,ARG3,ARG4))
#define ERROR_5(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5) ERROR(FORMAT_5(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5))
#define ERROR_6(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6) ERROR(FORMAT_6(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6))
#define ERROR_7(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7) ERROR(FORMAT_7(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7))
#define ERROR_8(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7,ARG8) ERROR(FORMAT_8(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7,ARG8))

#define ERROR_NO_IMPLEMENTATION ERROR("No Implementation")

#else

#define ERROR(MESSAGE) /* disabled */
#define ERROR_1(MESSAGE,ARG1) /* disabled */
#define ERROR_2(MESSAGE,ARG1,ARG2) /* disabled */
#define ERROR_3(MESSAGE,ARG1,ARG2,ARG3) /* disabled */
#define ERROR_4(MESSAGE,ARG1,ARG2,ARG3,ARG4) /* disabled */
#define ERROR_5(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5) /* disabled */
#define ERROR_6(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6) /* disabled */
#define ERROR_7(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7) /* disabled */
#define ERROR_8(MESSAGE,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7,ARG8) /* disabled */

#define ERROR_NO_IMPLEMENTATION /* disabled */

#endif

#define FORMAT_1(STR,ARG1) format[STR, ARG1]
#define FORMAT_2(STR,ARG1,ARG2) format[STR, ARG1, ARG2]
#define FORMAT_3(STR,ARG1,ARG2,ARG3) format[STR, ARG1, ARG2, ARG3]
#define FORMAT_4(STR,ARG1,ARG2,ARG3,ARG4) format[STR, ARG1, ARG2, ARG3, ARG4]
#define FORMAT_5(STR,ARG1,ARG2,ARG3,ARG4,ARG5) format[STR, ARG1, ARG2, ARG3, ARG4, ARG5]
#define FORMAT_6(STR,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6) format[STR, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6]
#define FORMAT_7(STR,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7) format[STR, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7]
#define FORMAT_8(STR,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7,ARG8) format[STR, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8]

#endif


